import React from 'react';
import { SlideEmbedding } from '../types.js';
import { FileText, BookOpen, Layers, Sparkles, ExternalLink, Hash, CheckCircle2 } from 'lucide-react';

interface SlideViewerProps {
  slide: SlideEmbedding | null;
  onClose?: () => void;
}

export const SlideViewer: React.FC<SlideViewerProps> = ({ slide, onClose }) => {
  if (!slide) {
    return (
      <div className="h-full flex flex-col items-center justify-center p-8 text-center text-slate-500 border border-dashed border-slate-800 rounded-2xl bg-slate-900/20">
        <BookOpen className="w-12 h-12 text-slate-700 mb-3" />
        <h4 className="text-sm font-semibold text-slate-400">No Slide Selected</h4>
        <p className="text-xs text-slate-500 max-w-xs mt-1">
          Click on any citation in the chat or search lecture slides via Supabase pgvector.
        </p>
      </div>
    );
  }

  return (
    <div className="rounded-2xl border border-indigo-500/30 bg-slate-900/90 shadow-2xl overflow-hidden flex flex-col h-full">
      {/* Slide Presentation Header Bar */}
      <div className="p-4 bg-gradient-to-r from-slate-900 via-indigo-950/40 to-slate-900 border-b border-slate-800 flex items-center justify-between">
        <div className="flex items-center gap-2.5">
          <div className="w-8 h-8 rounded-lg bg-indigo-500/20 border border-indigo-500/30 flex items-center justify-center text-indigo-400 font-bold text-xs">
            #{slide.page_number}
          </div>
          <div>
            <div className="flex items-center gap-2">
              <span className="px-2 py-0.5 rounded bg-indigo-500/20 text-indigo-300 font-mono text-[11px] font-semibold border border-indigo-500/30">
                {slide.course_code}
              </span>
              <span className="text-xs text-slate-400 flex items-center gap-1 font-mono">
                <FileText className="w-3 h-3 text-slate-500" />
                {slide.document_name}
              </span>
            </div>
            <h3 className="text-sm font-bold text-slate-100 mt-0.5 line-clamp-1">
              {slide.title}
            </h3>
          </div>
        </div>

        {slide.similarity !== undefined && (
          <div className="flex items-center gap-1 px-2.5 py-1 rounded-full bg-emerald-500/10 border border-emerald-500/30 text-emerald-400 text-xs font-mono font-medium">
            <Sparkles className="w-3.5 h-3.5 text-emerald-400" />
            <span>{(slide.similarity * 100).toFixed(1)}% Match</span>
          </div>
        )}
      </div>

      {/* Slide Body Canvas */}
      <div className="p-5 flex-1 overflow-y-auto space-y-4">
        {/* Presentation Slide Visual Preview Card */}
        <div className="p-5 rounded-xl bg-slate-950 border border-slate-800 shadow-inner relative">
          <div className="absolute top-3 right-3 text-[10px] text-slate-600 font-mono flex items-center gap-1">
            <Layers className="w-3 h-3" />
            <span>SLIDE CANVAS • PGVECTOR 768-DIM</span>
          </div>

          <div className="mb-3">
            <span className="text-[11px] font-bold text-indigo-400 uppercase tracking-wider">
              Lecture Slide Content:
            </span>
            <h4 className="text-base font-bold text-white mt-1">
              {slide.title}
            </h4>
          </div>

          <div className="text-sm leading-relaxed text-slate-200 font-sans whitespace-pre-wrap bg-slate-900/50 p-4 rounded-lg border border-slate-800/80">
            {slide.content}
          </div>

          {/* Key Topics / Tags */}
          <div className="mt-4 pt-3 border-t border-slate-800 flex flex-wrap items-center gap-1.5">
            <span className="text-[11px] text-slate-500 font-medium mr-1">Concept Tags:</span>
            {slide.tags.map((tag, i) => (
              <span
                key={i}
                className="px-2 py-0.5 rounded-md bg-slate-800/80 text-slate-300 text-[11px] font-mono border border-slate-700/60"
              >
                #{tag}
              </span>
            ))}
          </div>
        </div>

        {/* Verification Certificate */}
        <div className="p-3.5 rounded-xl bg-emerald-950/20 border border-emerald-800/30 flex items-start gap-3 text-xs text-emerald-300">
          <CheckCircle2 className="w-4 h-4 text-emerald-400 shrink-0 mt-0.5" />
          <div>
            <div className="font-semibold text-emerald-200">
              Supabase pgvector Verified Reference
            </div>
            <div className="text-emerald-400/80 text-[11.5px] mt-0.5">
              This slide chunk is indexed in the university lecture repository. Citations generated by StudySync AI strictly bound responses to these contents to eliminate hallucination.
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};
